#!/usr/bin/env python3
"""Regenerate the manuscript's numeric tables from ``data/``, and diff them against the note.

Two outputs:

``tables/tab_*.tex``
    Standalone ``tabular`` fragments with the same columns and the same number of digits as
    the typeset tables.  They are not ``\\input`` by the manuscript -- the note carries its
    tables inline, so that it reads on its own -- but they make the typeset numbers
    diffable against the data that produced them.

``tables/DIFF_REPORT.md``
    Exactly that diff.  The corresponding ``tabular`` environments are parsed out of the
    manuscript by label, their numeric cells extracted, and each compared with the freshly
    computed value at the precision the manuscript prints.  This is how a transcription error
    gets found: the claims checker verifies that the *data* is right, this verifies that what
    was *typed into the paper* matches the data.

Usage
    python scripts/10_tables.py [--note manuscript/note.tex] [--outdir tables]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA = REPO_ROOT / "data"
NOTE_CANDIDATES = ("manuscript/note.tex", "handoff/note.tex")


def load(name: str) -> Dict[str, Any]:
    path = DATA / name
    if not path.exists():
        raise SystemExit(f"{path} is missing; run the experiment that produces it first.")
    return json.loads(path.read_text())


def tabular(colspec: str, header: Sequence[str], rows: Sequence[Sequence[str]], caption: str) -> str:
    lines = [
        f"% generated by scripts/10_tables.py -- {caption}",
        f"\\begin{{tabular}}{{@{{}}{colspec}@{{}}}}",
        "\\toprule",
        " & ".join(header) + "\\\\",
        "\\midrule",
    ]
    lines += [" & ".join(r) + "\\\\" for r in rows]
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines).rstrip("\n") + "\n"


def sci(x: float, digits: int = 1) -> str:
    """``1.3e-08`` as ``$1.3\\times10^{-8}$``."""
    if x == 0:
        return "$0$"
    s = f"{x:.{digits}e}"
    mant, exp = s.split("e")
    return f"${mant}\\times10^{{{int(exp)}}}$"


# ------------------------------------------------------------------ tables ----
def tab_valid() -> Tuple[str, List[float]]:
    kin = load("01_kinetic.json")
    fold = load("04_fold.json")
    rows = [
        [r"velocity of the maximum of $\sigma$, $\chat$", f"${kin['critical']['c_hat1']:.7f}$", "$0.8989$"],
        [r"maximal force $\sigma(\chat)$", f"${kin['critical']['sigma_hat1']:.7f}$", "$0.65019$"],
        [r"maximal velocity (turning point), $\cmax$", f"${fold['c_max']:.6f}$", "$0.9002$"],
    ]
    nums = [kin["critical"]["c_hat1"], kin["critical"]["sigma_hat1"], fold["c_max"]]
    return tabular("lll", ["quantity", "this note", r"\cite{VCKX20}"], rows, "Table 2"), nums


def tab_conv() -> Tuple[str, List[float]]:
    conv = load("02_identity.json")["convergence"]
    order = ["L200_N1024", "L200_N2048", "L200_N4096", "L300_N3072", "L300_N6144", "L150_N2048"]
    rows, nums = [], []
    for key in order:
        rec = conv.get(key)
        if rec is None:
            continue
        L = rec.get("L", float(key.split("_")[0][1:]))
        N = rec.get("N", float(key.split("_")[1][1:]))
        h = 2 * L / N
        rows.append([f"{L:.0f}", f"{N:.0f}", f"{h:.3f}", sci(rec["relerr"]), sci(rec["res_M0p0"])])
        nums += [L, N, h, rec["relerr"], rec["res_M0p0"]]
    header = ["$L$", "$N$", "$h$", "relative error of~\\eqref{eq:identity}",
              r"$\|M_0\phi'\|_\infty/\|\phi'\|_\infty$"]
    return tabular("rrrcc", header, rows, "Table 3"), nums


def tab_threshold() -> Tuple[str, List[float]]:
    thr = load("03_threshold.json")["rows"]
    rows, nums = [], []
    for key in sorted(thr):
        r = thr[key]
        nu2 = r["nu2"]
        rows.append([
            f"{r['c']:.5f}",
            f"${r['sigma_prime']:+.7f}$",
            f"${r['kappa']:+.7f}$",
            f"${r['m']:.1f}$",
            "(invalid)" if r["m"] < 0 else f"${r['nu2_pred']:+.6f}$",
            "---" if nu2 is None else f"${nu2:+.6f}$",
            "---" if nu2 is None else f"{r['rho2']:.5f}",
        ])
        nums += [r["c"], r["sigma_prime"], r["kappa"], r["m"]]
    header = ["$c$", r"$\sigma'(c)$", r"$\kappa$", "$m$", r"$-\kappa/m$", r"$\nu_2$", r"$\rho_2$"]
    return tabular("lrrrrrl", header, rows, "Table 4"), nums


def tab_fold() -> Tuple[str, List[float]]:
    fold = load("04_fold.json")
    sampled = [(int(k), v) for k, v in fold["rows"].items() if v.get("nu") is not None]
    fold_step = fold.get("fold_step")
    if fold_step is not None:
        sampled = [kv for kv in sampled if abs(kv[0] - float(fold_step)) <= 2.5]
    sampled.sort()
    rows, nums = [], []
    for step, r in sampled:
        rows.append([
            str(step), f"{r['c']:.6f}", f"{r['sigma']:.6f}", sci(r["cdot"], 2),
            f"${r['kappa']:+.5f}$", f"${r['phat_one']:+.6f}$",
            f"{r['nu']:.5f} ({r['nu'] and __import__('math').exp(r['nu'] / r['c']):.5f})",
        ])
        nums += [r["c"], r["sigma"], r["cdot"], r["kappa"], r["phat_one"], r["nu"]]
    header = ["step", "$c$", r"$\sigma$", r"$\dot c$", r"$\kappa$",
              r"$\ip{\ph}{\one}$", r"$\nu$ ($\rho$)"]
    return tabular("rllrrrl", header, rows, "Table 5"), nums


def tab_decay() -> Tuple[str, List[float]]:
    nv = load("05_nullvec.json")["decay"]
    stations = sorted((k for k in nv if k.lstrip("-").isdigit()), key=lambda s: int(s))
    header = ["$|\\xi|$"] + [s for s in stations]
    rows = [
        ["$\\phi'$"] + [sci(nv[s]["p0"]) for s in stations],
        ["$\\ph$"] + [sci(nv[s]["phat"]) for s in stations],
    ]
    nums = [nv[s]["p0"] for s in stations] + [nv[s]["phat"] for s in stations]
    return tabular("l" + "r" * len(stations), header, rows, "Table 6"), nums


def tab_gen() -> Tuple[str, List[float]]:
    gen = load("08_general.json")["rows"]
    labels = {
        "fk": r"FK, $\mu=1$", "mu2m05": r"$\mu_2=-0.5$", "nnn": r"$C_2=0.25$",
        "mu2nnn": r"$\mu_2=0.3$, $C_2=0.2$", "soft": r"$\mu=0.6$, $\gamma=0.2$",
    }
    rows, nums = [], []
    for key, label in labels.items():
        if key not in gen:
            continue
        r = gen[key]
        rows.append([label, f"{r['f']:.6f}", f"{r['fprime']:.6f}", f"{r['kappa']:.6f}",
                     f"{r['pred']:.6f}", sci(r["relerr"])])
        nums += [r["f"], r["fprime"], r["kappa"], r["pred"], r["relerr"]]
    header = ["lattice", "$f$", "$f'(c)$", r"$\kappa$", r"$-f'\ip{\ph}{\one}$", "rel.\\ error"]
    return tabular("lrrrrr", header, rows, "Table 7"), nums


TABLES = {
    "tab_valid": (tab_valid, "tab:valid"),
    "tab_conv": (tab_conv, "tab:conv"),
    "tab_threshold": (tab_threshold, "tab:threshold"),
    "tab_fold": (tab_fold, "tab:fold"),
    "tab_decay": (tab_decay, "tab:decay"),
    "tab_gen": (tab_gen, "tab:gen"),
}


# -------------------------------------------------------------------- diff ----
NUM_RE = re.compile(r"[-+]?\d+\.?\d*(?:\\times10\^\{[-+]?\d+\}|[eE][-+]?\d+)?")


def _to_float(token: str) -> float | None:
    token = token.replace("\\times10^{", "e").replace("}", "")
    try:
        return float(token)
    except ValueError:
        return None


def _printed_ulp(token: str) -> float:
    """Half a unit in the last digit the manuscript actually printed.

    The comparison has to be made at the precision of the typeset number, not at the
    precision of the computation: ``3.1\\times10^{-4}`` in the paper and ``3.0495e-4`` in the
    data agree perfectly well, and a fixed relative tolerance would call that a mismatch while
    missing a genuine transcription error in a number printed to seven digits.
    """
    token = token.replace("\\times10^{", "e").replace("}", "")
    mantissa, _, exponent = token.partition("e")
    decimals = len(mantissa.split(".")[1]) if "." in mantissa else 0
    scale = 10.0 ** int(exponent) if exponent else 1.0
    return 0.5 * (10.0 ** -decimals) * scale


def manuscript_numbers(note_text: str, label: str) -> List[Tuple[float, float]]:
    """``(value, tolerance)`` for every number inside the ``tabular`` carrying ``label``."""
    idx = note_text.find("\\label{" + label + "}")
    if idx < 0:
        return []
    start = note_text.find("\\begin{tabular}", idx)
    end = note_text.find("\\end{tabular}", start)
    if start < 0 or end < 0:
        return []
    body = note_text[start:end]
    body = body.split("\\midrule", 1)[-1]
    out = []
    for token in NUM_RE.findall(body):
        value = _to_float(token)
        if value is not None:
            out.append((value, _printed_ulp(token)))
    return out


def diff_report(note_path: Path, generated: Dict[str, List[float]]) -> str:
    text = note_path.read_text()
    lines = [
        "# Table diff: manuscript against regenerated data",
        "",
        f"Manuscript: `{note_path.relative_to(REPO_ROOT)}`.",
        "",
        "Each table's numeric cells are extracted from the typeset `tabular` and from the "
        "freshly generated fragment, then compared as sets at the precision the manuscript "
        "prints. The claims checker verifies that the data is right; this verifies that what "
        "was typed into the paper matches the data.",
        "",
    ]
    total_missing = 0
    for name, (_, label) in TABLES.items():
        if name not in generated:
            continue
        typeset = manuscript_numbers(text, label)
        fresh = generated[name]
        if not typeset:
            lines += [f"## {name} (`{label}`)", "", "Table not found in the manuscript.", ""]
            continue
        missing = []
        for value in fresh:
            if not any(abs(value - t) <= max(tol, 1e-12) for t, tol in typeset):
                missing.append(value)
        total_missing += len(missing)
        lines += [f"## {name} (`{label}`)", "",
                  f"- regenerated cells: {len(fresh)}; numbers found in the typeset table: {len(typeset)}",
                  f"- regenerated values with no match in the manuscript: **{len(missing)}**", ""]
        if missing:
            lines += ["| regenerated value |", "|---|"]
            lines += [f"| `{v:.10g}` |" for v in missing]
            lines.append("")
    lines.insert(
        6,
        f"**{total_missing} regenerated value(s) have no counterpart in the typeset tables.**\n"
        if total_missing
        else "**Every regenerated value has a counterpart in the typeset tables.**\n",
    )
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--note", default=None, help="manuscript to diff against")
    parser.add_argument("--outdir", default="tables")
    args = parser.parse_args(argv)

    note_path = Path(args.note) if args.note else None
    if note_path is None:
        for candidate in NOTE_CANDIDATES:
            if (REPO_ROOT / candidate).exists():
                note_path = REPO_ROOT / candidate
                break
    if note_path is None or not note_path.exists():
        raise SystemExit(f"no manuscript found; looked for {NOTE_CANDIDATES}")

    outdir = REPO_ROOT / args.outdir
    outdir.mkdir(parents=True, exist_ok=True)
    generated: Dict[str, List[float]] = {}
    for name, (builder, _) in TABLES.items():
        try:
            text, nums = builder()
        except SystemExit as exc:
            print(f"  skipping {name}: {exc}")
            continue
        (outdir / f"{name}.tex").write_text(text)
        generated[name] = nums
        print(f"  wrote {(outdir / f'{name}.tex').relative_to(REPO_ROOT)}")

    report = outdir / "DIFF_REPORT.md"
    report.write_text(diff_report(note_path, generated))
    print(f"  wrote {report.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
